{% set name = "dagster_spark" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 4a61e44a1afddf011681895bfa4db7bb6c281dcca0ce86076433ec4f28f84a87

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*

test:
  imports:
    - dagster_spark

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-spark
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Package for Spark Dagster framework components.

extra:
  recipe-maintainers:
    - conda-forge/dagster
